{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "http://poc-nb.us-east-1.nwac-dev.net/qod/v0"
    }
  ],
  "tags": [
    {
      "name": "sessions"
    }
  ],
  "paths": {
    "/sessions/{sessionId}": {
      "get": {
        "tags": [
          "sessions"
        ],
        "summary": "Return QoS settings.",
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sessionid"
            }
          }
        ],
        "operationId": "getSession",
        "description": "Return device communication bandwidth (QoS) settings.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {
                      "id": "",
                      "qosProfile": "",
                      "qosStatus": "",
                      "startedAt": {},
                      "expiresAt": {}
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "id": {
                      "type": "string",
                      "title": "Id",
                      "description": "ID of the created resource."
                    },
                    "qosProfile": {
                      "type": "string",
                      "title": "Qosprofile",
                      "description": "Name of the QoS profile."
                    },
                    "qosStatus": {
                      "type": "string",
                      "title": "Qosstatus",
                      "description": "Status of the QoS resource. REQUESTED, AVAILABLE or UNAVAILABLE"
                    },
                    "startedAt": {
                      "anyOf": [
                        {
                          "type": "integer"
                        },
                        {
                          "nullable": true
                        }
                      ],
                      "title": "Startedat",
                      "description": "Timestamp of session start in seconds since unix epoch"
                    },
                    "expiresAt": {
                      "anyOf": [
                        {
                          "type": "integer"
                        },
                        {
                          "nullable": true
                        }
                      ],
                      "title": "Expiresat",
                      "description": "Timestamp of session expiration if the session was not deleted, in seconds since unix epoch"
                    }
                  },
                  "type": "object",
                  "required": [
                    "id",
                    "qosProfile",
                    "qosStatus"
                  ],
                  "title": "SessionInfo"
                }
              }
            },
            "description": ""
          },
          "422": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {
                      "detail": [
                        {
                          "loc": [],
                          "msg": "",
                          "type": ""
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "detail": {
                      "items": {
                        "properties": {
                          "loc": {
                            "items": {
                              "anyOf": [
                                {
                                  "type": "string"
                                },
                                {
                                  "type": "integer"
                                }
                              ]
                            },
                            "type": "array",
                            "title": "Location"
                          },
                          "msg": {
                            "type": "string",
                            "title": "Message"
                          },
                          "type": {
                            "type": "string",
                            "title": "Error Type"
                          }
                        },
                        "type": "object",
                        "required": [
                          "loc",
                          "msg",
                          "type"
                        ],
                        "title": "ValidationError"
                      },
                      "type": "array",
                      "title": "Detail"
                    }
                  },
                  "type": "object",
                  "title": "HTTPValidationError"
                }
              }
            },
            "description": ""
          }
        }
      }
    },
    "/sessions": {
      "post": {
        "tags": [
          "sessions"
        ],
        "summary": "Create QoS service",
        "operationId": "createSession",
        "description": "Create device communication bandwidth (QoS) service.",
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {
                      "id": "",
                      "qosProfile": "",
                      "qosStatus": "",
                      "startedAt": {},
                      "expiresAt": {}
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "id": {
                      "type": "string",
                      "title": "Id",
                      "description": "ID of the created resource."
                    },
                    "qosProfile": {
                      "type": "string",
                      "title": "Qosprofile",
                      "description": "Name of the QoS profile."
                    },
                    "qosStatus": {
                      "type": "string",
                      "title": "Qosstatus",
                      "description": "Status of the QoS resource. REQUESTED, AVAILABLE or UNAVAILABLE"
                    },
                    "startedAt": {
                      "anyOf": [
                        {
                          "type": "integer"
                        },
                        {
                          "nullable": true
                        }
                      ],
                      "title": "Startedat",
                      "description": "Timestamp of session start in seconds since unix epoch"
                    },
                    "expiresAt": {
                      "anyOf": [
                        {
                          "type": "integer"
                        },
                        {
                          "nullable": true
                        }
                      ],
                      "title": "Expiresat",
                      "description": "Timestamp of session expiration if the session was not deleted, in seconds since unix epoch"
                    }
                  },
                  "type": "object",
                  "required": [
                    "id",
                    "qosProfile",
                    "qosStatus"
                  ],
                  "title": "SessionInfo"
                }
              }
            },
            "description": ""
          },
          "422": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {
                      "detail": [
                        {
                          "loc": [],
                          "msg": "",
                          "type": ""
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "detail": {
                      "items": {
                        "properties": {
                          "loc": {
                            "items": {
                              "anyOf": [
                                {
                                  "type": "string"
                                },
                                {
                                  "type": "integer"
                                }
                              ]
                            },
                            "type": "array",
                            "title": "Location"
                          },
                          "msg": {
                            "type": "string",
                            "title": "Message"
                          },
                          "type": {
                            "type": "string",
                            "title": "Error Type"
                          }
                        },
                        "type": "object",
                        "required": [
                          "loc",
                          "msg",
                          "type"
                        ],
                        "title": "ValidationError"
                      },
                      "type": "array",
                      "title": "Detail"
                    }
                  },
                  "type": "object",
                  "title": "HTTPValidationError"
                }
              }
            },
            "description": ""
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example_1": {
                  "value": {
                    "qosProfile": "",
                    "device": {
                      "phoneNumber": {},
                      "networkAccessIdentifier": {},
                      "ipv4Address": {
                        "publicAddress": {},
                        "privateAddress": {},
                        "publicPort": {}
                      },
                      "ipv6Address": {}
                    },
                    "id": {},
                    "ip": {},
                    "devicePorts": {
                      "ranges": {
                        "0": {
                          "from": 0,
                          "to": 0
                        }
                      },
                      "ports": {}
                    },
                    "applicationServer": {
                      "ipv4Address": {},
                      "ipv6Address": {}
                    },
                    "appIp": {},
                    "applicationServerPorts": {
                      "ranges": {
                        "0": {
                          "from": 0,
                          "to": 0
                        }
                      },
                      "ports": {}
                    },
                    "duration": {},
                    "notificationUrl": {},
                    "notificationAuthToken": {}
                  }
                }
              },
              "schema": {
                "properties": {
                  "qosProfile": {
                    "type": "string",
                    "title": "Qosprofile",
                    "description": "Name of the requested QoS profile."
                  },
                  "device": {
                    "anyOf": [
                      {
                        "properties": {
                          "phoneNumber": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Phonenumber"
                          },
                          "networkAccessIdentifier": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Networkaccessidentifier"
                          },
                          "ipv4Address": {
                            "anyOf": [
                              {
                                "properties": {
                                  "publicAddress": {
                                    "anyOf": [
                                      {
                                        "type": "string"
                                      },
                                      {
                                        "nullable": true
                                      }
                                    ],
                                    "title": "Publicaddress",
                                    "description": "Public IPv4 address of the device. Either of the device or the NAT the device is behind."
                                  },
                                  "privateAddress": {
                                    "anyOf": [
                                      {
                                        "type": "string"
                                      },
                                      {
                                        "nullable": true
                                      }
                                    ],
                                    "title": "Privateaddress",
                                    "description": "Private IPv4 address of the device, if it is behind a NAT."
                                  },
                                  "publicPort": {
                                    "anyOf": [
                                      {
                                        "type": "integer"
                                      },
                                      {
                                        "nullable": true
                                      }
                                    ],
                                    "title": "Publicport",
                                    "description": "Public port used by the device. Port is necessary, as private address ranges overlap, and public port is used to extend the range for CGNAT."
                                  }
                                },
                                "type": "object",
                                "title": "DeviceIpv4Addr"
                              },
                              {
                                "nullable": true
                              }
                            ]
                          },
                          "ipv6Address": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ipv6Address"
                          }
                        },
                        "type": "object",
                        "title": "Device"
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "description": "Identifiers of the device"
                  },
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "title": "Id",
                    "description": "Identifier of the device"
                  },
                  "ip": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "title": "Ip",
                    "description": "IP address of the device"
                  },
                  "devicePorts": {
                    "anyOf": [
                      {
                        "properties": {
                          "ranges": {
                            "anyOf": [
                              {
                                "items": {
                                  "properties": {
                                    "from": {
                                      "type": "integer",
                                      "maximum": 65535,
                                      "minimum": 1,
                                      "title": "From",
                                      "description": "Start of port range."
                                    },
                                    "to": {
                                      "type": "integer",
                                      "maximum": 65535,
                                      "minimum": 1,
                                      "title": "To",
                                      "description": "End of port range."
                                    }
                                  },
                                  "type": "object",
                                  "required": [
                                    "from",
                                    "to"
                                  ],
                                  "title": "PortsSpecRangesInner"
                                },
                                "type": "array"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ranges"
                          },
                          "ports": {
                            "anyOf": [
                              {
                                "items": {
                                  "type": "integer"
                                },
                                "type": "array"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ports",
                            "description": "List of port numbers the application may use. Optional."
                          }
                        },
                        "type": "object",
                        "title": "PortsSpec"
                      },
                      {
                        "nullable": true
                      }
                    ]
                  },
                  "applicationServer": {
                    "anyOf": [
                      {
                        "properties": {
                          "ipv4Address": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ipv4Address"
                          },
                          "ipv6Address": {
                            "anyOf": [
                              {
                                "type": "string"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ipv6Address"
                          }
                        },
                        "type": "object",
                        "title": "ApplicationServer"
                      },
                      {
                        "nullable": true
                      }
                    ]
                  },
                  "appIp": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "title": "Appip",
                    "description": "IP address of the application"
                  },
                  "applicationServerPorts": {
                    "anyOf": [
                      {
                        "properties": {
                          "ranges": {
                            "anyOf": [
                              {
                                "items": {
                                  "properties": {
                                    "from": {
                                      "type": "integer",
                                      "maximum": 65535,
                                      "minimum": 1,
                                      "title": "From",
                                      "description": "Start of port range."
                                    },
                                    "to": {
                                      "type": "integer",
                                      "maximum": 65535,
                                      "minimum": 1,
                                      "title": "To",
                                      "description": "End of port range."
                                    }
                                  },
                                  "type": "object",
                                  "required": [
                                    "from",
                                    "to"
                                  ],
                                  "title": "PortsSpecRangesInner"
                                },
                                "type": "array"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ranges"
                          },
                          "ports": {
                            "anyOf": [
                              {
                                "items": {
                                  "type": "integer"
                                },
                                "type": "array"
                              },
                              {
                                "nullable": true
                              }
                            ],
                            "title": "Ports",
                            "description": "List of port numbers the application may use. Optional."
                          }
                        },
                        "type": "object",
                        "title": "PortsSpec"
                      },
                      {
                        "nullable": true
                      }
                    ]
                  },
                  "duration": {
                    "anyOf": [
                      {
                        "type": "integer",
                        "maximum": 86400,
                        "minimum": 1
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "title": "Duration",
                    "description": "Session duration in seconds."
                  },
                  "notificationUrl": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "title": "Notificationurl",
                    "description": "Notification URL for session-related events."
                  },
                  "notificationAuthToken": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "nullable": true
                      }
                    ],
                    "title": "Notificationauthtoken",
                    "description": "Authorization token for notification sending."
                  }
                },
                "type": "object",
                "required": [
                  "qosProfile"
                ],
                "title": "CreateSession"
              }
            }
          },
          "description": ""
        }
      },
      "get": {
        "tags": [
          "sessions"
        ],
        "summary": "Return QoS settings for your device.",
        "parameters": [
          {
            "name": "device-id",
            "in": "query",
            "required": true,
            "description": "Device ID",
            "schema": {
              "type": "string",
              "description": "Device ID",
              "title": "Device-Id"
            }
          }
        ],
        "operationId": "getAllSessions",
        "description": "Return device communication bandwidth (QoS) settings for your device.",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": [
                      {
                        "id": "",
                        "qosProfile": "",
                        "qosStatus": "",
                        "startedAt": {},
                        "expiresAt": {}
                      }
                    ]
                  }
                },
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "type": "string",
                        "title": "Id",
                        "description": "ID of the created resource."
                      },
                      "qosProfile": {
                        "type": "string",
                        "title": "Qosprofile",
                        "description": "Name of the QoS profile."
                      },
                      "qosStatus": {
                        "type": "string",
                        "title": "Qosstatus",
                        "description": "Status of the QoS resource. REQUESTED, AVAILABLE or UNAVAILABLE"
                      },
                      "startedAt": {
                        "anyOf": [
                          {
                            "type": "integer"
                          },
                          {
                            "nullable": true
                          }
                        ],
                        "title": "Startedat",
                        "description": "Timestamp of session start in seconds since unix epoch"
                      },
                      "expiresAt": {
                        "anyOf": [
                          {
                            "type": "integer"
                          },
                          {
                            "nullable": true
                          }
                        ],
                        "title": "Expiresat",
                        "description": "Timestamp of session expiration if the session was not deleted, in seconds since unix epoch"
                      }
                    },
                    "type": "object",
                    "required": [
                      "id",
                      "qosProfile",
                      "qosStatus"
                    ],
                    "title": "SessionInfo"
                  },
                  "title": "Response Getallsessions"
                }
              }
            },
            "description": ""
          },
          "422": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {
                      "detail": [
                        {
                          "loc": [],
                          "msg": "",
                          "type": ""
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "detail": {
                      "items": {
                        "properties": {
                          "loc": {
                            "items": {
                              "anyOf": [
                                {
                                  "type": "string"
                                },
                                {
                                  "type": "integer"
                                }
                              ]
                            },
                            "type": "array",
                            "title": "Location"
                          },
                          "msg": {
                            "type": "string",
                            "title": "Message"
                          },
                          "type": {
                            "type": "string",
                            "title": "Error Type"
                          }
                        },
                        "type": "object",
                        "required": [
                          "loc",
                          "msg",
                          "type"
                        ],
                        "title": "ValidationError"
                      },
                      "type": "array",
                      "title": "Detail"
                    }
                  },
                  "type": "object",
                  "title": "HTTPValidationError"
                }
              }
            },
            "description": ""
          }
        }
      }
    },
    "/sessions/{id}": {
      "delete": {
        "tags": [
          "sessions"
        ],
        "summary": "Delete Qos Handler",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Id"
            }
          }
        ],
        "operationId": "deleteSession",
        "description": " ",
        "responses": {
          "204": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {}
                  }
                },
                "schema": {}
              }
            },
            "description": ""
          },
          "422": {
            "content": {
              "application/json": {
                "examples": {
                  "Example_1": {
                    "value": {
                      "detail": [
                        {
                          "loc": [],
                          "msg": "",
                          "type": ""
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "detail": {
                      "items": {
                        "properties": {
                          "loc": {
                            "items": {
                              "anyOf": [
                                {
                                  "type": "string"
                                },
                                {
                                  "type": "integer"
                                }
                              ]
                            },
                            "type": "array",
                            "title": "Location"
                          },
                          "msg": {
                            "type": "string",
                            "title": "Message"
                          },
                          "type": {
                            "type": "string",
                            "title": "Error Type"
                          }
                        },
                        "type": "object",
                        "required": [
                          "loc",
                          "msg",
                          "type"
                        ],
                        "title": "ValidationError"
                      },
                      "type": "array",
                      "title": "Detail"
                    }
                  },
                  "type": "object",
                  "title": "HTTPValidationError"
                }
              }
            },
            "description": ""
          }
        }
      }
    }
  },
  "info": {
    "title": "QoS on Demand",
    "version": "0.1.0",
    "description": "Manage QoS sessions for users on demand.",
    "x-category": "Connectivity",
    "x-long-description": "Manage QoS sessions for users on demand.",
    "x-website": "",
    "x-public": true,
    "x-thumbnail": "https://rapidapi-prod-prodeu-apis.s3.eu-central-1.amazonaws.com/3d49db2b-0fd5-44e6-a5b2-d08e01293b9c.png",
    "x-version-lifecycle": "active",
    "x-badges": [
      {
        "name": "Technology",
        "value": "REST"
      }
    ],
    "x-collections": [
      "Network as Code APIs"
    ]
  },
  "components": {
    "securitySchemes": {
      "RapidApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "X-RapidAPI-Key"
      }
    },
    "schemas": {
      "ApplicationServer": {
        "properties": {
          "ipv4Address": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Ipv4Address"
          },
          "ipv6Address": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Ipv6Address"
          }
        },
        "type": "object",
        "title": "ApplicationServer"
      },
      "CreateSession": {
        "properties": {
          "qosProfile": {
            "type": "string",
            "title": "Qosprofile",
            "description": "Name of the requested QoS profile."
          },
          "device": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/Device"
              },
              {
                "nullable": true
              }
            ],
            "description": "Identifiers of the device"
          },
          "id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Id",
            "description": "Identifier of the device"
          },
          "ip": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Ip",
            "description": "IP address of the device"
          },
          "devicePorts": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/PortsSpec"
              },
              {
                "nullable": true
              }
            ]
          },
          "applicationServer": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/ApplicationServer"
              },
              {
                "nullable": true
              }
            ]
          },
          "appIp": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Appip",
            "description": "IP address of the application"
          },
          "applicationServerPorts": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/PortsSpec"
              },
              {
                "nullable": true
              }
            ]
          },
          "duration": {
            "anyOf": [
              {
                "type": "integer",
                "maximum": 86400,
                "minimum": 1
              },
              {
                "nullable": true
              }
            ],
            "title": "Duration",
            "description": "Session duration in seconds."
          },
          "notificationUrl": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Notificationurl",
            "description": "Notification URL for session-related events."
          },
          "notificationAuthToken": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Notificationauthtoken",
            "description": "Authorization token for notification sending."
          }
        },
        "type": "object",
        "required": [
          "qosProfile"
        ],
        "title": "CreateSession"
      },
      "Device": {
        "properties": {
          "phoneNumber": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Phonenumber"
          },
          "networkAccessIdentifier": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Networkaccessidentifier"
          },
          "ipv4Address": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/DeviceIpv4Addr"
              },
              {
                "nullable": true
              }
            ]
          },
          "ipv6Address": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Ipv6Address"
          }
        },
        "type": "object",
        "title": "Device"
      },
      "DeviceIpv4Addr": {
        "properties": {
          "publicAddress": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Publicaddress",
            "description": "Public IPv4 address of the device. Either of the device or the NAT the device is behind."
          },
          "privateAddress": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "nullable": true
              }
            ],
            "title": "Privateaddress",
            "description": "Private IPv4 address of the device, if it is behind a NAT."
          },
          "publicPort": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "nullable": true
              }
            ],
            "title": "Publicport",
            "description": "Public port used by the device. Port is necessary, as private address ranges overlap, and public port is used to extend the range for CGNAT."
          }
        },
        "type": "object",
        "title": "DeviceIpv4Addr"
      },
      "EventDetail": {
        "properties": {
          "sessionId": {
            "type": "string",
            "title": "Sessionid"
          },
          "qosStatus": {
            "$ref": "#/components/schemas/EventQosStatus"
          },
          "statusInfo": {
            "$ref": "#/components/schemas/StatusInfo"
          }
        },
        "type": "object",
        "required": [
          "sessionId",
          "qosStatus",
          "statusInfo"
        ],
        "title": "EventDetail"
      },
      "EventNotification": {
        "properties": {
          "event": {
            "$ref": "#/components/schemas/QosStatusChangedEvent"
          }
        },
        "type": "object",
        "required": [
          "event"
        ],
        "title": "EventNotification",
        "description": "Quality on Demand event notification."
      },
      "EventQosStatus": {
        "type": "string",
        "enum": [
          "AVAILABLE",
          "UNAVAILABLE"
        ],
        "title": "EventQosStatus"
      },
      "EventType": {
        "type": "string",
        "title": "EventType",
        "enum": [
          "QOS_STATUS_CHANGED"
        ]
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
      "PortsSpec": {
        "properties": {
          "ranges": {
            "anyOf": [
              {
                "items": {
                  "$ref": "#/components/schemas/PortsSpecRangesInner"
                },
                "type": "array"
              },
              {
                "nullable": true
              }
            ],
            "title": "Ranges"
          },
          "ports": {
            "anyOf": [
              {
                "items": {
                  "type": "integer"
                },
                "type": "array"
              },
              {
                "nullable": true
              }
            ],
            "title": "Ports",
            "description": "List of port numbers the application may use. Optional."
          }
        },
        "type": "object",
        "title": "PortsSpec"
      },
      "PortsSpecRangesInner": {
        "properties": {
          "from": {
            "type": "integer",
            "maximum": 65535,
            "minimum": 1,
            "title": "From",
            "description": "Start of port range."
          },
          "to": {
            "type": "integer",
            "maximum": 65535,
            "minimum": 1,
            "title": "To",
            "description": "End of port range."
          }
        },
        "type": "object",
        "required": [
          "from",
          "to"
        ],
        "title": "PortsSpecRangesInner"
      },
      "QosStatusChangedEvent": {
        "properties": {
          "eventType": {
            "$ref": "#/components/schemas/EventType"
          },
          "eventTime": {
            "type": "string",
            "title": "Eventtime",
            "description": "Time of the event"
          },
          "eventDetail": {
            "$ref": "#/components/schemas/EventDetail"
          }
        },
        "type": "object",
        "required": [
          "eventType",
          "eventTime",
          "eventDetail"
        ],
        "title": "QosStatusChangedEvent"
      },
      "SessionInfo": {
        "properties": {
          "id": {
            "type": "string",
            "title": "Id",
            "description": "ID of the created resource."
          },
          "qosProfile": {
            "type": "string",
            "title": "Qosprofile",
            "description": "Name of the QoS profile."
          },
          "qosStatus": {
            "type": "string",
            "title": "Qosstatus",
            "description": "Status of the QoS resource. REQUESTED, AVAILABLE or UNAVAILABLE"
          },
          "startedAt": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "nullable": true
              }
            ],
            "title": "Startedat",
            "description": "Timestamp of session start in seconds since unix epoch"
          },
          "expiresAt": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "nullable": true
              }
            ],
            "title": "Expiresat",
            "description": "Timestamp of session expiration if the session was not deleted, in seconds since unix epoch"
          }
        },
        "type": "object",
        "required": [
          "id",
          "qosProfile",
          "qosStatus"
        ],
        "title": "SessionInfo"
      },
      "StatusInfo": {
        "type": "string",
        "enum": [
          "DURATION_EXPIRED",
          "NETWORK_TERMINATED"
        ],
        "title": "StatusInfo"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "type": "array",
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "type": "object",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError"
      }
    }
  },
  "x-gateways": [],
  "x-documentation": {
    "readme": "",
    "tutorials": [],
    "spotlights": []
  },
  "x-rapidapi-info": {
    "apiVersionId": "apiversion_7ed28d41-a07c-4822-8df3-dbcc03031fe5",
    "apiId": "api_4a29b891-bd80-4ed4-ba11-51f980685e16"
  },
  "security": [
    {
       "RapidApiKey": []
    }
  ]
}
